version: '3.3'

services:
  db:
    build: ./mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - ./config/db.env
    networks:
      - back-net

  wordpress:
    depends_on:
      - db
    build: ./wordpress
    ports:
      - "8080:80"
    restart: always
    env_file:
      - ./config/wp.env
    networks:
      - back-net

volumes:
  db_data: {}
networks:
  back-net:
    driver: bridge
